# Generated by Django 5.2.9 on 2026-08-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0003_contactmessage_alter_contact_id_alter_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
