# Generated by Django 5.2.9 on 2026-08-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0004_contact_is_read_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
