# Generated by Django 5.2.9 on 2026-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0005_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='solar_products/images/')),
                ('pdf', models.FileField(upload_to='solar_products/pdfs/')),
            ],
        ),
    ]
