# Generated by Django 5.2.9 on 2026-08-15 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0006_solarproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solarproduct',
            name='image',
            field=models.ImageField(upload_to='solar_products/'),
        ),
        migrations.AlterField(
            model_name='solarproduct',
            name='name2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solarproduct',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='solar_products/pdf/'),
        ),
    ]
