# Generated by Django 5.2.9 on 2026-08-15 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0007_solarproduct_created_at_alter_solarproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
