# Generated by Django 5.2.9 on 2026-08-15 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0009_solarinverter_alter_contactmessage_id_alter_page_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='battery_storage/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='battery_storage/pdf/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
