# Generated by Django 5.2.9 on 2026-08-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0010_batterystorage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarinverter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='solarinverter',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='solarinverter',
            name='name2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='SolarInverterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='solar_inverters/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sungreen_solar.solarinverter')),
            ],
        ),
        migrations.CreateModel(
            name='SolarInverterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='solar_inverters/pdfs/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='sungreen_solar.solarinverter')),
            ],
        ),
    ]
