# Generated by Django 5.2.9 on 2026-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0011_remove_solarinverter_image_remove_solarinverter_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarinverter',
            options={},
        ),
        migrations.AlterField(
            model_name='solarinverter',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solarinverter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarinverter',
            name='name2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='solarinverterpdf',
            name='title',
            field=models.CharField(default='PDF Document', max_length=255),
        ),
    ]
