# Generated by Django 5.2.9 on 2026-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0012_alter_solarinverter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sungreen Solar', max_length=200)),
                ('site_tagline', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
