# Generated by Django 5.2.9 on 2026-08-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0013_websitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='solar_products/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solar Product Image',
                'verbose_name_plural': 'Solar Product Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolarProductPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PDF Document', max_length=255)),
                ('pdf', models.FileField(upload_to='solar_products/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solar Product PDF',
                'verbose_name_plural': 'Solar Product PDFs',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WebsiteSetting',
        ),
        migrations.AlterModelOptions(
            name='solarproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solar Product', 'verbose_name_plural': 'Solar Products'},
        ),
        migrations.RemoveField(
            model_name='solarproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='solarproduct',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='solarproduct',
            name='name2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solarproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sungreen_solar.solarproduct'),
        ),
        migrations.AddField(
            model_name='solarproductpdf',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='sungreen_solar.solarproduct'),
        ),
    ]
