# Generated by Django 5.2.9 on 2026-08-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0014_solarproductimage_solarproductpdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='solarproductimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='solarproductpdf',
            options={},
        ),
        migrations.AlterField(
            model_name='solarproductpdf',
            name='title',
            field=models.CharField(default='Product Brochure', max_length=255),
        ),
    ]
