# Generated by Django 5.2.9 on 2026-08-23 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0015_alter_solarproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterystorage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='batterystorage',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='batterystorage',
            name='name2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='BatteryStorageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='battery_storage/images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sungreen_solar.batterystorage')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryStoragePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('pdf', models.FileField(upload_to='battery_storage/pdf/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='sungreen_solar.batterystorage')),
            ],
        ),
    ]
