# Generated by Django 6.0.1 on 2026-08-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0018_review_delete_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterystorage',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='batterystorage',
            name='inverter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
