# Generated by Django 6.0.1 on 2026-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0022_finish_battery_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batterystoragecategory',
            options={'ordering': ['name'], 'verbose_name': 'Battery Storage Category', 'verbose_name_plural': 'Battery Storage Categories'},
        ),
        migrations.AlterField(
            model_name='batterystorage',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
