# Generated by Django 6.0.1 on 2026-08-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0023_alter_batterystoragecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterystorage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery_storages', to='sungreen_solar.batterystoragecategory'),
        ),
    ]
