# Generated by Django 6.0.1 on 2026-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0024_alter_batterystorage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterystorage',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='batterystorage',
            name='inverter',
        ),
        migrations.AddField(
            model_name='batterystorage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='battery_storage/'),
        ),
        migrations.AddField(
            model_name='batterystorage',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='battery_storage/pdfs/'),
        ),
        migrations.AddField(
            model_name='batterystorage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='batterystorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='batterystorage',
            name='name1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='batterystorage',
            name='name2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='batterystorageimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='batterystoragepdf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='batterystoragepdf',
            name='pdf',
            field=models.FileField(upload_to='battery_storage/pdfs/'),
        ),
        migrations.AlterField(
            model_name='batterystoragepdf',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='BatteryStorageCategory',
        ),
    ]
