# Generated by Django 5.2.9 on 2026-08-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0025_alter_batterystorage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarproduct',
            name='category',
            field=models.CharField(default='Solar Panels', max_length=100),
        ),
    ]
