# Generated by Django 6.0.1 on 2026-08-29 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungreen_solar', '0027_mountingkit_alter_solarproduct_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVCharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255, verbose_name='Product Name')),
                ('name2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Subtitle')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ev_chargers/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='ev_chargers/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EVChargerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ev_chargers/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sungreen_solar.evcharger')),
            ],
        ),
        migrations.CreateModel(
            name='EVChargerPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(upload_to='ev_chargers/pdfs/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='sungreen_solar.evcharger')),
            ],
        ),
    ]
